<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use App\Models\Brand;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Get categories and brands
        $rawMaterials = Category::where('name', 'Raw Materials')->first();
        $dairyFeedTwingalick = Category::where('name', 'Dairy Feed - Twingalick')->first();
        $mineralSupplements = Category::where('name', 'Mineral Supplements')->first();

        $twingalick = Brand::where('name', 'Twingalick')->first();
        $generic = Brand::where('name', 'Generic')->first();

        $products = [
            // ===== RAW MATERIALS =====
            [
                'name' => 'Wheat Bran 40kg',
                'sku' => 'WB-40',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'High quality wheat bran for animal feed. Rich in fiber and nutrients.',
                'unit' => '40kg bag',
                'quantity_in_stock' => 100,
                'reorder_level' => 20,
                'price' => 1800.00,
                'min_selling_price' => 1700.00,
                'max_selling_price' => 1900.00,
                'wholesale_price' => 1650.00,
                'cost_price' => 1500.00,
                'barcode' => '8901234567001',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Maize Germ – Grand 50kg',
                'sku' => 'MG-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Premium maize germ for high energy animal feed formulation.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 80,
                'reorder_level' => 15,
                'price' => 2200.00,
                'min_selling_price' => 2100.00,
                'max_selling_price' => 2300.00,
                'wholesale_price' => 2050.00,
                'cost_price' => 1900.00,
                'barcode' => '8901234567002',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Pollard 10kg',
                'sku' => 'PL-10',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Fine wheat pollard for feed mixing. Excellent source of fiber.',
                'unit' => '10kg bag',
                'quantity_in_stock' => 150,
                'reorder_level' => 30,
                'price' => 550.00,
                'min_selling_price' => 520.00,
                'max_selling_price' => 580.00,
                'wholesale_price' => 500.00,
                'cost_price' => 450.00,
                'barcode' => '8901234567003',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Pollard 20kg',
                'sku' => 'PL-20',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Fine wheat pollard for feed mixing. Excellent source of fiber.',
                'unit' => '20kg bag',
                'quantity_in_stock' => 120,
                'reorder_level' => 25,
                'price' => 1050.00,
                'min_selling_price' => 1000.00,
                'max_selling_price' => 1100.00,
                'wholesale_price' => 950.00,
                'cost_price' => 850.00,
                'barcode' => '8901234567004',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Cotton Seed Cake',
                'sku' => 'CSC-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'High protein cotton seed cake for livestock feed.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 60,
                'reorder_level' => 15,
                'price' => 2500.00,
                'min_selling_price' => 2400.00,
                'max_selling_price' => 2600.00,
                'wholesale_price' => 2350.00,
                'cost_price' => 2200.00,
                'barcode' => '8901234567005',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Soya Bean Meal',
                'sku' => 'SBM-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Premium soya bean meal. Excellent protein source for animal feed.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 90,
                'reorder_level' => 20,
                'price' => 3200.00,
                'min_selling_price' => 3100.00,
                'max_selling_price' => 3300.00,
                'wholesale_price' => 3000.00,
                'cost_price' => 2800.00,
                'barcode' => '8901234567006',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Sunflower Seed Cake',
                'sku' => 'SSC-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Sunflower seed cake for balanced animal nutrition.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 70,
                'reorder_level' => 15,
                'price' => 2400.00,
                'min_selling_price' => 2300.00,
                'max_selling_price' => 2500.00,
                'wholesale_price' => 2250.00,
                'cost_price' => 2100.00,
                'barcode' => '8901234567007',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Canola Meal',
                'sku' => 'CM-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Canola meal for high-quality animal feed formulation.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 50,
                'reorder_level' => 15,
                'price' => 2800.00,
                'min_selling_price' => 2700.00,
                'max_selling_price' => 2900.00,
                'wholesale_price' => 2650.00,
                'cost_price' => 2450.00,
                'barcode' => '8901234567008',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Lime (White)',
                'sku' => 'LW-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Agricultural lime for calcium supplementation in animal feed.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 40,
                'reorder_level' => 10,
                'price' => 800.00,
                'min_selling_price' => 750.00,
                'max_selling_price' => 850.00,
                'wholesale_price' => 720.00,
                'cost_price' => 650.00,
                'barcode' => '8901234567009',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'DCP (Di-Calcium Phosphate)',
                'sku' => 'DCP-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Di-Calcium Phosphate for bone development and milk production.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 35,
                'reorder_level' => 10,
                'price' => 3500.00,
                'min_selling_price' => 3400.00,
                'max_selling_price' => 3600.00,
                'wholesale_price' => 3300.00,
                'cost_price' => 3100.00,
                'barcode' => '8901234567010',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Maize Grover',
                'sku' => 'MV-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Whole maize grains for livestock feed.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 200,
                'reorder_level' => 40,
                'price' => 2000.00,
                'min_selling_price' => 1900.00,
                'max_selling_price' => 2100.00,
                'wholesale_price' => 1850.00,
                'cost_price' => 1700.00,
                'barcode' => '8901234567011',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Bone Meal',
                'sku' => 'BM-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Bone meal for calcium and phosphorus supplementation.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 30,
                'reorder_level' => 10,
                'price' => 2600.00,
                'min_selling_price' => 2500.00,
                'max_selling_price' => 2700.00,
                'wholesale_price' => 2450.00,
                'cost_price' => 2300.00,
                'barcode' => '8901234567012',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Fish Meal',
                'sku' => 'FM-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'High protein fish meal for poultry and livestock.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 25,
                'reorder_level' => 10,
                'price' => 4500.00,
                'min_selling_price' => 4400.00,
                'max_selling_price' => 4600.00,
                'wholesale_price' => 4300.00,
                'cost_price' => 4000.00,
                'barcode' => '8901234567013',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Maize Flour',
                'sku' => 'MF-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Fine maize flour for feed formulation.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 100,
                'reorder_level' => 25,
                'price' => 2100.00,
                'min_selling_price' => 2000.00,
                'max_selling_price' => 2200.00,
                'wholesale_price' => 1950.00,
                'cost_price' => 1800.00,
                'barcode' => '8901234567014',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Omena (Dried Fish)',
                'sku' => 'OM-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Dried omena for protein supplementation in animal feed.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 20,
                'reorder_level' => 8,
                'price' => 5500.00,
                'min_selling_price' => 5400.00,
                'max_selling_price' => 5600.00,
                'wholesale_price' => 5300.00,
                'cost_price' => 5000.00,
                'barcode' => '8901234567015',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Rice Bran',
                'sku' => 'RB-50',
                'category_id' => $rawMaterials->id,
                'brand_id' => $generic->id,
                'description' => 'Rice bran for energy and fiber in animal feed.',
                'unit' => '50kg bag',
                'quantity_in_stock' => 60,
                'reorder_level' => 15,
                'price' => 1600.00,
                'min_selling_price' => 1500.00,
                'max_selling_price' => 1700.00,
                'wholesale_price' => 1450.00,
                'cost_price' => 1300.00,
                'barcode' => '8901234567016',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],

            // ===== TWINGALICK BLACK BRICK =====
            [
                'name' => 'Twingalick Black Brick 8kg - Box (8 pcs)',
                'sku' => 'TW-BB-8BOX',
                'category_id' => $mineralSupplements->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Black Brick mineral lick. One box contains 8 pieces of 1kg each.',
                'unit' => '1 box (8 pcs)',
                'quantity_in_stock' => 50,
                'reorder_level' => 10,
                'price' => 1600.00,
                'min_selling_price' => 1550.00,
                'max_selling_price' => 1650.00,
                'wholesale_price' => 1500.00,
                'cost_price' => 1400.00,
                'barcode' => '8901234568001',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],

            // ===== TWINGALICK BRICK =====
            [
                'name' => 'Twingalick Brick 5kg',
                'sku' => 'TW-BR-5',
                'category_id' => $mineralSupplements->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Brick 5kg mineral supplement for livestock.',
                'unit' => '5kg brick',
                'quantity_in_stock' => 80,
                'reorder_level' => 15,
                'price' => 1000.00,
                'min_selling_price' => 950.00,
                'max_selling_price' => 1050.00,
                'wholesale_price' => 920.00,
                'cost_price' => 850.00,
                'barcode' => '8901234568002',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Brick 1kg',
                'sku' => 'TW-BR-1',
                'category_id' => $mineralSupplements->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Brick 1kg mineral supplement for livestock.',
                'unit' => '1kg brick',
                'quantity_in_stock' => 200,
                'reorder_level' => 40,
                'price' => 220.00,
                'min_selling_price' => 200.00,
                'max_selling_price' => 240.00,
                'wholesale_price' => 190.00,
                'cost_price' => 170.00,
                'barcode' => '8901234568003',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],

            // ===== TWINGALICK NDAMA =====
            [
                'name' => 'Twingalick Ndama 1kg - Bale (10 pcs)',
                'sku' => 'TW-ND-1B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Ndama 1kg dairy feed. One bale contains 10 pieces.',
                'unit' => '1 bale (10 pcs)',
                'quantity_in_stock' => 60,
                'reorder_level' => 15,
                'price' => 2200.00,
                'min_selling_price' => 2100.00,
                'max_selling_price' => 2300.00,
                'wholesale_price' => 2050.00,
                'cost_price' => 1900.00,
                'barcode' => '8901234569001',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Ndama 2kg - Bale (10 pcs)',
                'sku' => 'TW-ND-2B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Ndama 2kg dairy feed. One bale contains 10 pieces.',
                'unit' => '1 bale (10 pcs)',
                'quantity_in_stock' => 45,
                'reorder_level' => 12,
                'price' => 4200.00,
                'min_selling_price' => 4100.00,
                'max_selling_price' => 4300.00,
                'wholesale_price' => 4000.00,
                'cost_price' => 3700.00,
                'barcode' => '8901234569002',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Ndama 5kg - Bale (4 pcs)',
                'sku' => 'TW-ND-5B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Ndama 5kg dairy feed. One bale contains 4 pieces.',
                'unit' => '1 bale (4 pcs)',
                'quantity_in_stock' => 30,
                'reorder_level' => 10,
                'price' => 4000.00,
                'min_selling_price' => 3900.00,
                'max_selling_price' => 4100.00,
                'wholesale_price' => 3800.00,
                'cost_price' => 3500.00,
                'barcode' => '8901234569003',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],

            // ===== TWINGALICK MAZIWA JOTO =====
            [
                'name' => 'Twingalick Maziwa Joto 1kg - Bale (10 pcs)',
                'sku' => 'TW-MJ-1B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Joto 1kg dairy feed. One bale contains 10 pieces.',
                'unit' => '1 bale (10 pcs)',
                'quantity_in_stock' => 70,
                'reorder_level' => 15,
                'price' => 2300.00,
                'min_selling_price' => 2200.00,
                'max_selling_price' => 2400.00,
                'wholesale_price' => 2150.00,
                'cost_price' => 2000.00,
                'barcode' => '8901234570001',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Joto 2kg - Bale (10 pcs)',
                'sku' => 'TW-MJ-2B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Joto 2kg dairy feed. One bale contains 10 pieces.',
                'unit' => '1 bale (10 pcs)',
                'quantity_in_stock' => 55,
                'reorder_level' => 12,
                'price' => 4400.00,
                'min_selling_price' => 4300.00,
                'max_selling_price' => 4500.00,
                'wholesale_price' => 4200.00,
                'cost_price' => 3900.00,
                'barcode' => '8901234570002',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Joto 5kg - Bale (4 pcs)',
                'sku' => 'TW-MJ-5B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Joto 5kg dairy feed. One bale contains 4 pieces.',
                'unit' => '1 bale (4 pcs)',
                'quantity_in_stock' => 35,
                'reorder_level' => 10,
                'price' => 4200.00,
                'min_selling_price' => 4100.00,
                'max_selling_price' => 4300.00,
                'wholesale_price' => 4000.00,
                'cost_price' => 3700.00,
                'barcode' => '8901234570003',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],

            // ===== TWINGALICK MAZIWA COW =====
            [
                'name' => 'Twingalick Maziwa Cow 1kg - Bale (10 pcs)',
                'sku' => 'TW-MC-1B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Cow 1kg dairy feed. One bale contains 10 pieces.',
                'unit' => '1 bale (10 pcs)',
                'quantity_in_stock' => 65,
                'reorder_level' => 15,
                'price' => 2400.00,
                'min_selling_price' => 2300.00,
                'max_selling_price' => 2500.00,
                'wholesale_price' => 2250.00,
                'cost_price' => 2100.00,
                'barcode' => '8901234571001',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Cow 2kg - Bale',
                'sku' => 'TW-MC-2B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Cow 2kg dairy feed bale.',
                'unit' => '1 bale',
                'quantity_in_stock' => 50,
                'reorder_level' => 12,
                'price' => 4500.00,
                'min_selling_price' => 4400.00,
                'max_selling_price' => 4600.00,
                'wholesale_price' => 4300.00,
                'cost_price' => 4000.00,
                'barcode' => '8901234571002',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Cow 5kg - Bale (4 pcs)',
                'sku' => 'TW-MC-5B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Cow 5kg dairy feed. One bale contains 4 pieces.',
                'unit' => '1 bale (4 pcs)',
                'quantity_in_stock' => 40,
                'reorder_level' => 10,
                'price' => 4300.00,
                'min_selling_price' => 4200.00,
                'max_selling_price' => 4400.00,
                'wholesale_price' => 4100.00,
                'cost_price' => 3800.00,
                'barcode' => '8901234571003',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],

            // ===== TWINGALICK MAZIWA ZAIDI =====
            [
                'name' => 'Twingalick Maziwa Zaidi 1kg - Bale (10 pcs)',
                'sku' => 'TW-MZ-1B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Zaidi 1kg dairy feed. One bale contains 10 pieces.',
                'unit' => '1 bale (10 pcs)',
                'quantity_in_stock' => 75,
                'reorder_level' => 18,
                'price' => 2500.00,
                'min_selling_price' => 2400.00,
                'max_selling_price' => 2600.00,
                'wholesale_price' => 2350.00,
                'cost_price' => 2200.00,
                'barcode' => '8901234572001',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Zaidi 2kg - Bale (10 pcs)',
                'sku' => 'TW-MZ-2B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Zaidi 2kg dairy feed. One bale contains 10 pieces.',
                'unit' => '1 bale (10 pcs)',
                'quantity_in_stock' => 60,
                'reorder_level' => 15,
                'price' => 4800.00,
                'min_selling_price' => 4700.00,
                'max_selling_price' => 4900.00,
                'wholesale_price' => 4600.00,
                'cost_price' => 4300.00,
                'barcode' => '8901234572002',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Zaidi 5kg - Bale (4 pcs)',
                'sku' => 'TW-MZ-5B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Zaidi 5kg dairy feed. One bale contains 4 pieces.',
                'unit' => '1 bale (4 pcs)',
                'quantity_in_stock' => 45,
                'reorder_level' => 12,
                'price' => 4600.00,
                'min_selling_price' => 4500.00,
                'max_selling_price' => 4700.00,
                'wholesale_price' => 4400.00,
                'cost_price' => 4100.00,
                'barcode' => '8901234572003',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Zaidi 10kg',
                'sku' => 'TW-MZ-10',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Zaidi 10kg dairy feed (10 pieces per carton).',
                'unit' => '10kg bag',
                'quantity_in_stock' => 100,
                'reorder_level' => 25,
                'price' => 2100.00,
                'min_selling_price' => 2000.00,
                'max_selling_price' => 2200.00,
                'wholesale_price' => 1950.00,
                'cost_price' => 1800.00,
                'barcode' => '8901234572004',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Zaidi 20kg',
                'sku' => 'TW-MZ-20',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Zaidi 20kg dairy feed (20 pieces per carton).',
                'unit' => '20kg bag',
                'quantity_in_stock' => 80,
                'reorder_level' => 20,
                'price' => 4000.00,
                'min_selling_price' => 3900.00,
                'max_selling_price' => 4100.00,
                'wholesale_price' => 3800.00,
                'cost_price' => 3500.00,
                'barcode' => '8901234572005',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],

            // ===== TWINGALICK MAZIWA MAX =====
            [
                'name' => 'Twingalick Maziwa Max 1kg - Bale (10 pcs)',
                'sku' => 'TW-MM-1B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Max 1kg premium dairy feed. One bale contains 10 pieces.',
                'unit' => '1 bale (10 pcs)',
                'quantity_in_stock' => 90,
                'reorder_level' => 20,
                'price' => 2700.00,
                'min_selling_price' => 2600.00,
                'max_selling_price' => 2800.00,
                'wholesale_price' => 2550.00,
                'cost_price' => 2400.00,
                'barcode' => '8901234573001',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Max 2kg - Bale (10 pcs)',
                'sku' => 'TW-MM-2B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Max 2kg premium dairy feed. One bale contains 10 pieces.',
                'unit' => '1 bale (10 pcs)',
                'quantity_in_stock' => 70,
                'reorder_level' => 18,
                'price' => 5200.00,
                'min_selling_price' => 5100.00,
                'max_selling_price' => 5300.00,
                'wholesale_price' => 5000.00,
                'cost_price' => 4700.00,
                'barcode' => '8901234573002',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Max 5kg - Bale (4 pcs)',
                'sku' => 'TW-MM-5B',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Max 5kg premium dairy feed. One bale contains 4 pieces.',
                'unit' => '1 bale (4 pcs)',
                'quantity_in_stock' => 50,
                'reorder_level' => 12,
                'price' => 5000.00,
                'min_selling_price' => 4900.00,
                'max_selling_price' => 5100.00,
                'wholesale_price' => 4800.00,
                'cost_price' => 4500.00,
                'barcode' => '8901234573003',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Max 10kg',
                'sku' => 'TW-MM-10',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Max 10kg premium dairy feed.',
                'unit' => '10kg bag',
                'quantity_in_stock' => 120,
                'reorder_level' => 30,
                'price' => 2400.00,
                'min_selling_price' => 2300.00,
                'max_selling_price' => 2500.00,
                'wholesale_price' => 2250.00,
                'cost_price' => 2100.00,
                'barcode' => '8901234573004',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Maziwa Max 20kg',
                'sku' => 'TW-MM-20',
                'category_id' => $dairyFeedTwingalick->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Maziwa Max 20kg premium dairy feed.',
                'unit' => '20kg bag',
                'quantity_in_stock' => 95,
                'reorder_level' => 25,
                'price' => 4600.00,
                'min_selling_price' => 4500.00,
                'max_selling_price' => 4700.00,
                'wholesale_price' => 4400.00,
                'cost_price' => 4100.00,
                'barcode' => '8901234573005',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],

            // ===== TWINGALICK KALICK =====
            [
                'name' => 'Twingalick Kalick 2kg - Bale (10 pcs)',
                'sku' => 'TW-KL-2B',
                'category_id' => $mineralSupplements->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Kalick 2kg mineral supplement. One bale contains 10 pieces.',
                'unit' => '1 bale (10 pcs)',
                'quantity_in_stock' => 55,
                'reorder_level' => 15,
                'price' => 3800.00,
                'min_selling_price' => 3700.00,
                'max_selling_price' => 3900.00,
                'wholesale_price' => 3600.00,
                'cost_price' => 3400.00,
                'barcode' => '8901234574001',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Kalick 5kg - Bale (4 pcs)',
                'sku' => 'TW-KL-5B',
                'category_id' => $mineralSupplements->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Kalick 5kg mineral supplement. One bale contains 4 pieces.',
                'unit' => '1 bale (4 pcs)',
                'quantity_in_stock' => 40,
                'reorder_level' => 12,
                'price' => 3600.00,
                'min_selling_price' => 3500.00,
                'max_selling_price' => 3700.00,
                'wholesale_price' => 3400.00,
                'cost_price' => 3200.00,
                'barcode' => '8901234574002',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
            [
                'name' => 'Twingalick Kalick 25kg',
                'sku' => 'TW-KL-25',
                'category_id' => $mineralSupplements->id,
                'brand_id' => $twingalick->id,
                'description' => 'Twingalick Kalick 25kg bulk mineral supplement.',
                'unit' => '25kg bag',
                'quantity_in_stock' => 30,
                'reorder_level' => 10,
                'price' => 4200.00,
                'min_selling_price' => 4100.00,
                'max_selling_price' => 4300.00,
                'wholesale_price' => 4000.00,
                'cost_price' => 3700.00,
                'barcode' => '8901234574003',
                'tax_rate' => 16.00,
                'status' => 'active',
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }

        $this->command->info('🎉 Successfully seeded ' . count($products) . ' products!');
        $this->command->info('');
        $this->command->info('📊 Stock Status:');
        $this->command->info('   ✓ In Stock (above reorder): ' . Product::where('quantity_in_stock', '>', 20)->count());
        $this->command->info('   ⚠ Low Stock (at/below reorder): ' . Product::lowStock()->count());
        $this->command->info('   ✗ Out of Stock: ' . Product::outOfStock()->count());
        $this->command->info('');
        $this->command->info('📦 Products by Category:');
        $this->command->info('   • Raw Materials: ' . Product::where('category_id', $rawMaterials->id)->count());
        $this->command->info('   • Dairy Feed - Twingalick: ' . Product::where('category_id', $dairyFeedTwingalick->id)->count());
        $this->command->info('   • Mineral Supplements: ' . Product::where('category_id', $mineralSupplements->id)->count());
    }
}
